chore: fix envar expansion.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -221,8 +221,8 @@ jobs:
             echo "Checking $CIRCLE_PROJECT_USERNAME"
             # N.B. second repository temporarily added for troubleshooting, TODO remove before PR merge
             repositories=["influxCommunity", "karel-rehor"]
-            if ! [[ ${repositories[*]} =~ "$CIRCLE_PROJECT_USERNAME" ]]; then
-              echo "Cannot run release from $CIRCLE_PROJECT_USERNAME.  Failing this step."
+            if ! [[ ${repositories[*]} =~ "${CIRCLE_PROJECT_USERNAME}" ]]; then
+              echo "Cannot run release from ${CIRCLE_PROJECT_USERNAME}.  Failing this step."
               exit 1
             else
               echo "Proceeding with release from ${CIRCLE_PROJECT_USERNAME}"
