chore: fix array definition in release job.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -220,7 +220,12 @@ jobs:
           command: |
             echo "Checking $CIRCLE_PROJECT_USERNAME"
             # N.B. second repository temporarily added for troubleshooting, TODO remove before PR merge
-            repositories=["influxCommunity", "karel-rehor"]
+            repositories=("influxCommunity", "karel-rehor")
+            if [ -z "${CIRCLE_PROJECT_USERNAME}" ]
+            then
+              echo "CIRCLE_PROJECT_USERNAME is undefined.  Cannot continue."
+              exit 1
+            fi
             if ! [[ ${repositories[*]} =~ "${CIRCLE_PROJECT_USERNAME}" ]]; then
               echo "Cannot run release from ${CIRCLE_PROJECT_USERNAME}.  Failing this step."
               exit 1
